[2025-07-02T08:50:09.758+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-02T08:50:09.772+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-07-02T07:58:00+00:00 [queued]>
[2025-07-02T08:50:09.776+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-07-02T07:58:00+00:00 [queued]>
[2025-07-02T08:50:09.779+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-07-02T08:50:09.789+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_trusted> on 2025-07-02 07:58:00+00:00
[2025-07-02T08:50:09.802+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1546) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-02T08:50:09.807+0000] {standard_task_runner.py:72} INFO - Started process 1552 to run task
[2025-07-02T08:50:09.807+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_trusted', 'scheduled__2025-07-02T07:58:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmpc21va7xl']
[2025-07-02T08:50:09.808+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask run_dbt_trusted
[2025-07-02T08:50:09.845+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-07-02T07:58:00+00:00 [running]> on host 24d4a3002b8f
[2025-07-02T08:50:09.903+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_trusted' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T07:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-02T07:58:00+00:00'
[2025-07-02T08:50:09.905+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-02T08:50:09.924+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-02T08:50:09.925+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:trusted']
[2025-07-02T08:50:09.944+0000] {subprocess.py:86} INFO - Output:
[2025-07-02T08:50:09.953+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-07-02T08:50:09.954+0000] {subprocess.py:93} INFO - + dbt run --select tag:trusted
[2025-07-02T08:50:13.870+0000] {subprocess.py:93} INFO - [0m08:50:13  Running with dbt=1.8.0
[2025-07-02T08:50:14.063+0000] {subprocess.py:93} INFO - [0m08:50:14  Registered adapter: postgres=1.8.2
[2025-07-02T08:50:14.382+0000] {subprocess.py:93} INFO - [0m08:50:14  Found 9 models, 10 sources, 428 macros
[2025-07-02T08:50:14.386+0000] {subprocess.py:93} INFO - [0m08:50:14
[2025-07-02T08:50:14.489+0000] {subprocess.py:93} INFO - [0m08:50:14  Concurrency: 1 threads (target='dev')
[2025-07-02T08:50:14.491+0000] {subprocess.py:93} INFO - [0m08:50:14
[2025-07-02T08:50:14.556+0000] {subprocess.py:93} INFO - [0m08:50:14  1 of 4 START sql table model driven_trusted.non_pii_data ....................... [RUN]
[2025-07-02T08:50:15.075+0000] {subprocess.py:93} INFO - [0m08:50:15  1 of 4 OK created sql table model driven_trusted.non_pii_data .................. [[32mSELECT 11072[0m in 0.52s]
[2025-07-02T08:50:15.077+0000] {subprocess.py:93} INFO - [0m08:50:15  2 of 4 START sql table model driven_trusted.payment_data ....................... [RUN]
[2025-07-02T08:50:15.127+0000] {subprocess.py:93} INFO - [0m08:50:15  2 of 4 OK created sql table model driven_trusted.payment_data .................. [[32mSELECT 1384[0m in 0.05s]
[2025-07-02T08:50:15.130+0000] {subprocess.py:93} INFO - [0m08:50:15  3 of 4 START sql table model driven_trusted.pii_data ........................... [RUN]
[2025-07-02T08:50:15.198+0000] {subprocess.py:93} INFO - [0m08:50:15  3 of 4 OK created sql table model driven_trusted.pii_data ...................... [[32mSELECT 11072[0m in 0.07s]
[2025-07-02T08:50:15.200+0000] {subprocess.py:93} INFO - [0m08:50:15  4 of 4 START sql table model driven_trusted.technical_data ..................... [RUN]
[2025-07-02T08:50:15.235+0000] {subprocess.py:93} INFO - [0m08:50:15  4 of 4 OK created sql table model driven_trusted.technical_data ................ [[32mSELECT 1384[0m in 0.03s]
[2025-07-02T08:50:15.249+0000] {subprocess.py:93} INFO - [0m08:50:15
[2025-07-02T08:50:15.249+0000] {subprocess.py:93} INFO - [0m08:50:15  Finished running 4 table models in 0 hours 0 minutes and 0.86 seconds (0.86s).
[2025-07-02T08:50:15.279+0000] {subprocess.py:93} INFO - [0m08:50:15
[2025-07-02T08:50:15.280+0000] {subprocess.py:93} INFO - [0m08:50:15  [32mCompleted successfully[0m
[2025-07-02T08:50:15.280+0000] {subprocess.py:93} INFO - [0m08:50:15
[2025-07-02T08:50:15.281+0000] {subprocess.py:93} INFO - [0m08:50:15  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[2025-07-02T09:56:50.338+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-02T09:56:50.402+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-02T09:56:50.404+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_raw_data_pipeline, task_id=run_dbt_trusted, run_id=scheduled__2025-07-02T07:58:00+00:00, execution_date=20250702T075800, start_date=20250702T085009, end_date=20250702T095650
[2025-07-02T09:56:50.438+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-02T09:56:50.460+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-02T09:56:50.461+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
